# Generated by Django 4.2.30 on 2026-06-09 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticResult',
            fields=[
                ('id_diagnostic', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='diagnostics/')),
                ('maladie_detectee', models.CharField(max_length=200)),
                ('confiance', models.FloatField()),
                ('ravageur_detecte', models.CharField(blank=True, max_length=200)),
                ('traitement_suggere', models.TextField(blank=True)),
                ('source_github', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_journal', models.ForeignKey(db_column='id_journal', on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='journal.journalplante')),
            ],
            options={
                'db_table': 'diagnostic_result',
            },
        ),
    ]
