# Generated by Django 6.0.6 on 2026-06-11 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('champs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plante',
            fields=[
                ('id_plante', models.AutoField(primary_key=True, serialize=False)),
                ('nom_plante', models.CharField(max_length=50)),
                ('variete', models.CharField(max_length=50)),
                ('date_plantation', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(blank=True, db_column='update_at', null=True)),
                ('id_champ', models.ForeignKey(db_column='id_champ', on_delete=django.db.models.deletion.CASCADE, to='champs.champ')),
            ],
            options={
                'db_table': 'plantes',
                'managed': True,
            },
        ),
    ]
