# Generated by Django 6.0.5 on 2026-06-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('champs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plante',
            fields=[
                ('id_plante', models.AutoField(primary_key=True, serialize=False)),
                ('nom_plante', models.CharField(max_length=50)),
                ('variete', models.CharField(max_length=50)),
                ('date_plantation', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='update_at', null=True, blank=True)),
                ('id_champ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champs.Champ', db_column='id_champ')),
            ],
            options={
                'db_table': 'plantes',
                'managed': True,
            },
        ),
    ]
