# Generated by Django 5.0.7 on 2026-06-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plante',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='plante',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_column='update_at', null=True),
        ),
    ]
