# Generated by Django 6.0.6 on 2026-06-11 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPlante',
            fields=[
                ('id_journal', models.AutoField(primary_key=True, serialize=False)),
                ('date_observation', models.DateField()),
                ('stade_croissance', models.CharField(max_length=100)),
                ('symptomes', models.CharField(max_length=150)),
                ('ravageur_suspecte', models.CharField(max_length=150)),
                ('maladie_suspecte', models.CharField(max_length=150)),
                ('session_uuid', models.CharField(max_length=150)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id_plante', models.ForeignKey(db_column='id_plante', on_delete=django.db.models.deletion.CASCADE, to='plantes.plante')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'journal_plante',
                'managed': True,
            },
        ),
    ]
