# Generated by Django 6.0.5 on 2026-06-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPlante',
            fields=[
                ('id_journal', models.AutoField(primary_key=True, serialize=False)),
                ('date_observation', models.DateField()),
                ('stade_croissance', models.CharField(max_length=100)),
                ('symptomes', models.CharField(max_length=150)),
                ('ravageur_suspecte', models.CharField(max_length=150)),
                ('maladie_suspecte', models.CharField(max_length=150)),
                ('session_uuid', models.CharField(max_length=150)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'journal_plante',
                'managed': False,
            },
        ),
    ]
