# Generated by Django 4.2 on 2026-06-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalplante',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
