# Generated by Django 4.2 on 2026-07-03 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id_commune', models.AutoField(primary_key=True, serialize=False)),
                ('nom_commune', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'commune',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id_province', models.AutoField(primary_key=True, serialize=False)),
                ('nom_province', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'province',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id_zone', models.AutoField(primary_key=True, serialize=False)),
                ('nom_zone', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id_commune', models.ForeignKey(db_column='id_commune', on_delete=django.db.models.deletion.CASCADE, to='localisation.commune')),
            ],
            options={
                'db_table': 'zone',
            },
        ),
        migrations.AddField(
            model_name='commune',
            name='id_province',
            field=models.ForeignKey(db_column='id_province', on_delete=django.db.models.deletion.CASCADE, to='localisation.province'),
        ),
    ]
