/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YieldRouteImport } from './routes/yield'
import { Route as VillageRouteImport } from './routes/village'
import { Route as TranslationQaRouteImport } from './routes/translation-qa'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SelfTestRouteImport } from './routes/self-test'
import { Route as ScoutRouteImport } from './routes/scout'
import { Route as ScanTroubleshootRouteImport } from './routes/scan-troubleshoot'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as OutbreaksRouteImport } from './routes/outbreaks'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as MapRouteImport } from './routes/map'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'

const YieldRoute = YieldRouteImport.update({
  id: '/yield',
  path: '/yield',
  getParentRoute: () => rootRouteImport,
} as any)
const VillageRoute = VillageRouteImport.update({
  id: '/village',
  path: '/village',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslationQaRoute = TranslationQaRouteImport.update({
  id: '/translation-qa',
  path: '/translation-qa',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfTestRoute = SelfTestRouteImport.update({
  id: '/self-test',
  path: '/self-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutRoute = ScoutRouteImport.update({
  id: '/scout',
  path: '/scout',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanTroubleshootRoute = ScanTroubleshootRouteImport.update({
  id: '/scan-troubleshoot',
  path: '/scan-troubleshoot',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const OutbreaksRoute = OutbreaksRouteImport.update({
  id: '/outbreaks',
  path: '/outbreaks',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/docs': typeof DocsRoute
  '/history': typeof HistoryRoute
  '/learn': typeof LearnRoute
  '/map': typeof MapRoute
  '/moderation': typeof ModerationRoute
  '/outbreaks': typeof OutbreaksRoute
  '/scan': typeof ScanRoute
  '/scan-troubleshoot': typeof ScanTroubleshootRoute
  '/scout': typeof ScoutRoute
  '/self-test': typeof SelfTestRoute
  '/settings': typeof SettingsRoute
  '/translation-qa': typeof TranslationQaRoute
  '/village': typeof VillageRoute
  '/yield': typeof YieldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/docs': typeof DocsRoute
  '/history': typeof HistoryRoute
  '/learn': typeof LearnRoute
  '/map': typeof MapRoute
  '/moderation': typeof ModerationRoute
  '/outbreaks': typeof OutbreaksRoute
  '/scan': typeof ScanRoute
  '/scan-troubleshoot': typeof ScanTroubleshootRoute
  '/scout': typeof ScoutRoute
  '/self-test': typeof SelfTestRoute
  '/settings': typeof SettingsRoute
  '/translation-qa': typeof TranslationQaRoute
  '/village': typeof VillageRoute
  '/yield': typeof YieldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/docs': typeof DocsRoute
  '/history': typeof HistoryRoute
  '/learn': typeof LearnRoute
  '/map': typeof MapRoute
  '/moderation': typeof ModerationRoute
  '/outbreaks': typeof OutbreaksRoute
  '/scan': typeof ScanRoute
  '/scan-troubleshoot': typeof ScanTroubleshootRoute
  '/scout': typeof ScoutRoute
  '/self-test': typeof SelfTestRoute
  '/settings': typeof SettingsRoute
  '/translation-qa': typeof TranslationQaRoute
  '/village': typeof VillageRoute
  '/yield': typeof YieldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/dashboard'
    | '/developer'
    | '/diagnostics'
    | '/docs'
    | '/history'
    | '/learn'
    | '/map'
    | '/moderation'
    | '/outbreaks'
    | '/scan'
    | '/scan-troubleshoot'
    | '/scout'
    | '/self-test'
    | '/settings'
    | '/translation-qa'
    | '/village'
    | '/yield'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/dashboard'
    | '/developer'
    | '/diagnostics'
    | '/docs'
    | '/history'
    | '/learn'
    | '/map'
    | '/moderation'
    | '/outbreaks'
    | '/scan'
    | '/scan-troubleshoot'
    | '/scout'
    | '/self-test'
    | '/settings'
    | '/translation-qa'
    | '/village'
    | '/yield'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/dashboard'
    | '/developer'
    | '/diagnostics'
    | '/docs'
    | '/history'
    | '/learn'
    | '/map'
    | '/moderation'
    | '/outbreaks'
    | '/scan'
    | '/scan-troubleshoot'
    | '/scout'
    | '/self-test'
    | '/settings'
    | '/translation-qa'
    | '/village'
    | '/yield'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DeveloperRoute: typeof DeveloperRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  DocsRoute: typeof DocsRoute
  HistoryRoute: typeof HistoryRoute
  LearnRoute: typeof LearnRoute
  MapRoute: typeof MapRoute
  ModerationRoute: typeof ModerationRoute
  OutbreaksRoute: typeof OutbreaksRoute
  ScanRoute: typeof ScanRoute
  ScanTroubleshootRoute: typeof ScanTroubleshootRoute
  ScoutRoute: typeof ScoutRoute
  SelfTestRoute: typeof SelfTestRoute
  SettingsRoute: typeof SettingsRoute
  TranslationQaRoute: typeof TranslationQaRoute
  VillageRoute: typeof VillageRoute
  YieldRoute: typeof YieldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yield': {
      id: '/yield'
      path: '/yield'
      fullPath: '/yield'
      preLoaderRoute: typeof YieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/village': {
      id: '/village'
      path: '/village'
      fullPath: '/village'
      preLoaderRoute: typeof VillageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translation-qa': {
      id: '/translation-qa'
      path: '/translation-qa'
      fullPath: '/translation-qa'
      preLoaderRoute: typeof TranslationQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-test': {
      id: '/self-test'
      path: '/self-test'
      fullPath: '/self-test'
      preLoaderRoute: typeof SelfTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout': {
      id: '/scout'
      path: '/scout'
      fullPath: '/scout'
      preLoaderRoute: typeof ScoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-troubleshoot': {
      id: '/scan-troubleshoot'
      path: '/scan-troubleshoot'
      fullPath: '/scan-troubleshoot'
      preLoaderRoute: typeof ScanTroubleshootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outbreaks': {
      id: '/outbreaks'
      path: '/outbreaks'
      fullPath: '/outbreaks'
      preLoaderRoute: typeof OutbreaksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DeveloperRoute: DeveloperRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  DocsRoute: DocsRoute,
  HistoryRoute: HistoryRoute,
  LearnRoute: LearnRoute,
  MapRoute: MapRoute,
  ModerationRoute: ModerationRoute,
  OutbreaksRoute: OutbreaksRoute,
  ScanRoute: ScanRoute,
  ScanTroubleshootRoute: ScanTroubleshootRoute,
  ScoutRoute: ScoutRoute,
  SelfTestRoute: SelfTestRoute,
  SettingsRoute: SettingsRoute,
  TranslationQaRoute: TranslationQaRoute,
  VillageRoute: VillageRoute,
  YieldRoute: YieldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
