# Generated by Django 6.0.6 on 2026-06-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champ',
            fields=[
                ('id_champ', models.AutoField(primary_key=True, serialize=False)),
                ('superficie', models.FloatField(blank=True, null=True)),
                ('source_eau', models.CharField(choices=[('Forage', 'Forage'), ('Pluie', 'Pluie'), ('Irrigation', 'Irrigation'), ('Riviere', 'Riviere')], max_length=20)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
            ],
            options={
                'db_table': 'champs',
                'managed': True,
            },
        ),
    ]
