# Generated by Django 4.2.30 on 2026-07-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champs', '0002_alter_champ_created_at_alter_champ_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='champ',
            name='azote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='champ',
            name='date_analyse',
            field=models.DateField(blank=True, db_column='date', null=True),
        ),
        migrations.AddField(
            model_name='champ',
            name='fertilite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='champ',
            name='humidite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='champ',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='soil_studies/'),
        ),
        migrations.AddField(
            model_name='champ',
            name='matiere_organique',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='champ',
            name='ph_sol',
            field=models.CharField(blank=True, db_column='py_sol', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='champ',
            name='phosphore',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='champ',
            name='potassium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='champ',
            name='rapport_analyse',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='champ',
            name='type_sol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
