# Generated by Django 4.2.30 on 2026-07-06 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('success', 'Succès'), ('failure', 'Échec')], default='pending', max_length=20, verbose_name='Statut de la transaction')),
                ('type', models.CharField(choices=[('payment', 'Paiement'), ('refund', 'Remboursement')], default='payment', max_length=20, verbose_name='Type de transaction')),
                ('provider', models.CharField(max_length=50, verbose_name='Fournisseur de paiement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='XOF', max_length=10, verbose_name='Devise')),
                ('reference', models.CharField(max_length=255, unique=True, verbose_name='Référence fournisseur')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message du fournisseur')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='Réponse brute')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to='payments.payment', verbose_name='Paiement associé')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
