# Generated by Django 6.0.5 on 2026-06-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('champs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudeSol',
            fields=[
                ('id_etude_sol', models.AutoField(primary_key=True, serialize=False)),
                ('date_analyse', models.DateField(db_column='date')),
                ('ph_sol', models.CharField(max_length=100, db_column='py_sol')),
                ('matiere_organique', models.CharField(max_length=100)),
                ('azote', models.CharField(max_length=100)),
                ('phosphore', models.CharField(max_length=100)),
                ('potassium', models.CharField(max_length=100)),
                ('humidite', models.CharField(max_length=100)),
                ('type_sol', models.CharField(max_length=100)),
                ('fertilite', models.CharField(max_length=100)),
                ('rapport_analyse', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_champ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champs.Champ', db_column='id_champ')),
            ],
            options={
                'db_table': 'etude_sol',
                'managed': True,
            },
        ),
    ]
