# Generated by Django 6.0.5 on 2026-06-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtudeSol',
            fields=[
                ('id_etude_sol', models.AutoField(primary_key=True, serialize=False)),
                ('date_analyse', models.DateField()),
                ('ph_sol', models.CharField(max_length=100)),
                ('matiere_organique', models.CharField(max_length=100)),
                ('azote', models.CharField(max_length=100)),
                ('phosphore', models.CharField(max_length=100)),
                ('potassium', models.CharField(max_length=100)),
                ('humidite', models.CharField(max_length=100)),
                ('type_sol', models.CharField(max_length=100)),
                ('fertilite', models.CharField(max_length=100)),
                ('rapport_analyse', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=100)),
                ('updated_at', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'etude_sol',
                'managed': False,
            },
        ),
    ]
