# Generated by Django 4.2 on 2026-06-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etude_sol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudesol',
            name='id_etude_sol',
            field=models.AutoField(db_column='id_etude_sol', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etudesol',
            name='rapport_analyse',
            field=models.CharField(max_length=500),
        ),
    ]
